// This file will contain default data models for users and chats.

export function getDefaultUser(name) {
  return {
    afk: -1,
    afkReason: "",
    age: -1,
    agility: 16,
    anakanjing: 0,
    anakcentaur: 0,
    anakgriffin: 0,
    anakkucing: 0,
    anakkuda: 0,
    anakkyubi: 0,
    anaknaga: 0,
    anakpancingan: 0,
    anakphonix: 0,
    anakrubah: 0,
    anakserigala: 0,
    anggur: 0,
    anjing: 0,
    anjinglastclaim: 0,
    antispam: 0,
    antispamlastclaim: 0,
    apel: 0,
    aqua: 0,
    arc: 0,
    arcdurability: 0,
    arlok: 0,
    armor: 0,
    armordurability: 0,
    armormonster: 0,
    as: 0,
    atm: 0,
    autolevelup: false, // Diambil dari blok if (user) karena lebih masuk akal defaultnya false, atau true sesuai aslinya? Disini saya set false dulu, bisa diubah jika perlu. Di kode asli if (user) { if (!("autolevelup" in user)) user.autolevelup = true }
    axe: 0,
    axedurability: 0,
    ayam: 0,
    ayamb: 0,
    ayambakar: 0,
    ayamg: 0,
    ayamgoreng: 0,
    babi: 0,
    babihutan: 0,
    babipanggang: 0,
    bandage: 0,
    bank: 0,
    banned: false,
    BannedReason: "",
    Banneduser: false,
    antiCall: true, // Default dari else block
    banteng: 0,
    batu: 0,
    bawal: 0,
    bawalbakar: 0,
    bayam: 0,
    berlian: 100, // Diambil dari else block, if block punya 10
    bibitanggur: 0,
    bibitapel: 0,
    bibitjeruk: 0,
    bibitmangga: 0,
    bibitpisang: 0,
    botol: 0,
    bow: 0,
    bowdurability: 0,
    boxs: 0,
    brick: 0,
    brokoli: 0,
    buaya: 0,
    buntal: 0,
    cat: 0,
    catlastfeed: 0,
    catngexp: 0, // ejaan catngexp vs catexp, saya ambil catngexp dari else
    centaur: 0,
    centaurexp: 0,
    centaurlastclaim: 0,
    centaurlastfeed: 0,
    clay: 0,
    coal: 0,
    coin: 0,
    common: 0,
    crystal: 0,
    cumi: 0,
    cupon: 0,
    diamond: 0, // if block tidak ada, else block 0
    dog: 0,
    dogexp: 0,
    doglastfeed: 0,
    dory: 0,
    dragon: 0,
    dragonexp: 0,
    dragonlastfeed: 0,
    emas: 0,
    emerald: 0,
    esteh: 0,
    exp: 0,
    expg: 0,
    exphero: 0,
    expired: 0, // Dari else block
    fishingrod: 0,
    fishingroddurability: 0,
    fortress: 0,
    fox: 0,
    foxexp: 0,
    foxlastfeed: 0,
    fullatm: Infinity,
    gadodado: 0,
    gajah: 0,
    gamemines: false,
    ganja: 0,
    gardenboxs: 0,
    gems: 0,
    glass: 0,
    gold: 0, // if block tidak ada, else block 0. Beda dengan emas?
    griffin: 0,
    griffinexp: 0,
    griffinlastclaim: 0,
    griffinlastfeed: 0,
    gulai: 0,
    gurita: 0,
    harimau: 0,
    haus: 100,
    healt: 100, // healt vs health, keduanya ada. Saya satukan ke health nanti. Untuk sekarang ikuti else.
    health: 100,
    healtmonster: 100, // healtmonster vs healthmonster.
    healthmonster: 0, // if block punya 0
    hero: 1,
    herolastclaim: 0,
    hiu: 0,
    horse: 0,
    horseexp: 0,
    horselastfeed: 0,
    ikan: 0,
    ikanbakar: 0,
    intelligence: 10, // Dari else block
    iron: 0,
    jagung: 0,
    jagungbakar: 0,
    jeruk: 0,
    job: "Pengangguran",
    joinlimit: 1,
    judilast: 0,
    kaleng: 0,
    kambing: 0,
    kangkung: 0,
    kapak: 0,
    kardus: 0,
    katana: 0,
    katanadurability: 0,
    kayu: 0,
    kentang: 0,
    kentanggoreng: 0,
    kepiting: 0,
    kepitingbakar: 0,
    kerbau: 0,
    kerjadelapan: 0,
    kerjadelapanbelas: 0,
    kerjadua: 0,
    kerjaduabelas: 0,
    kerjaduadelapan: 0,
    kerjaduadua: 0,
    kerjaduaempat: 0,
    kerjaduaenam: 0,
    kerjadualima: 0,
    kerjaduapuluh: 0,
    kerjaduasatu: 0,
    kerjaduasembilan: 0,
    kerjaduatiga: 0,
    kerjaduatujuh: 0,
    kerjaempat: 0,
    kerjaempatbelas: 0,
    kerjaenam: 0,
    kerjaenambelas: 0,
    kerjalima: 0,
    kerjalimabelas: 0,
    kerjasatu: 0,
    kerjasebelas: 0,
    kerjasembilan: 0,
    kerjasembilanbelas: 0,
    kerjasepuluh: 0,
    kerjatiga: 0,
    kerjatigabelas: 0,
    kerjatigapuluh: 0,
    kerjatujuh: 0,
    kerjatujuhbelas: 0,
    korbanngocok: 0,
    kubis: 0,
    kucing: 0,
    kucinglastclaim: 0,
    kuda: 0,
    kudalastclaim: 0,
    kumba: 0, // Dari else block
    kyubi: 0,
    kyubilastclaim: 0, // Beda dengan if block yg kyubiexp, kyubilastfeed
    labu: 0,
    laper: 100,
    lastadventure: 0,
    lastberbru: 0,
    lastberkebon: 0,
    lastbunga: 0,
    lastbunuhi: 0,
    lastclaim: 0,
    lastcode: 0,
    lastcodereg: 0, // Hanya di if block
    lastcrusade: 0,
    lastdagang: 0,
    lastduel: 0,
    lastlont: 0, // Hanya di else block
    lastdungeon: 0,
    lasteasy: 0,
    lastfight: 0,
    lastfishing: 0,
    lastgift: 0, // Hanya di if block
    lastgojek: 0,
    lastgrab: 0,
    lasthourly: 0,
    lasthunt: 0,
    lastIstigfar: 0, // Hanya di if block
    lastjb: 0,
    lastkill: 0,
    lastlink: 0,
    lastlumber: 0,
    lastmancingeasy: 0,
    lastmancingextreme: 0,
    lastmancinghard: 0,
    lastmancingnormal: 0,
    lastmining: 0,
    lastmisi: 0,
    lastmonthly: 0,
    lastmulung: 0,
    lastnambang: 0,
    lastnebang: 0,
    lastngocok: 0,
    lastngojek: 0,
    lastopen: 0,
    lastpekerjaan: 0,
    lastpotionclaim: 0,
    lastrampok: 0, // Hanya di if block
    lastramuanclaim: 0,
    lastrob: 0,
    lastroket: 0,
    lastsda: 0, // Hanya di if block
    lastseen: 0,
    lastSetStatus: 0,
    lastsironclaim: 0,
    lastsmancingclaim: 0,
    laststringclaim: 0,
    lastswordclaim: 0,
    lastturu: 0,
    lastwar: 0, // Hanya di if block
    lastwarpet: 0,
    lastweaponclaim: 0,
    lastweekly: 0,
    lastwork: 0,
    lbars: "[▒▒▒▒▒▒▒▒▒]",
    legendary: 0,
    lele: 0,
    leleb: 0,
    lelebakar: 0,
    leleg: 0,
    level: 0,
    limit: 250, // Diambil dari else block, if block punya 10
    limitjoinfree: 1,
    lion: 0,
    lionexp: 0,
    lionlastfeed: 0,
    lobster: 0,
    lumba: 0,
    magicwand: 0,
    magicwanddurability: 0,
    makanan: 0, // 'makanan' ada di if (!user.registered) dan juga di list utama. Diambil dari else.
    makanancentaur: 0,
    makanangriffin: 0,
    makanankyubi: 0,
    makanannaga: 0,
    makananpet: 0,
    makananphonix: 0,
    makananserigala: 0,
    mana: 20, // Dari else block
    mangga: 0,
    misi: "", // Dari else block
    money: 100, // Dari else block. if block punya 100 juga.
    monyet: 0,
    mythic: 0,
    naga: 0,
    nagalastclaim: 0,
    name: name, // Dari parameter fungsi
    net: 0,
    nila: 0,
    nilabakar: 0,
    catatan: "", // Dari else block
    ojekk: 0,
    oporayam: 0,
    orca: 0,
    owner: false, // Dari else block
    ownerTime: 0, // Dari else block. Beda dengan if block 'ownerDate'
    pancingan: 1,
    panda: 0,
    pasangan: "", // Dari else block
    paus: 0,
    pausbakar: 0,
    pc: 0,
    pepesikan: 0,
    pet: 0, // if block tidak ada, else block 0
    petFood: 0, // if block tidak ada, else block 0
    phonix: 0,
    phonixexp: 0,
    phonixlastclaim: 0,
    phonixlastfeed: 0,
    pickaxe: 0,
    pickaxedurability: 0,
    pillhero: 0,
    pisang: 0,
    pointxp: 0,
    potion: 10, // Dari else block
    premium: false, // Dari else block
    premiumTime: 0, // Dari else block
    psenjata: 0, // Hanya di if block
    psepick: 0, // Hanya di if block
    ramuan: 0,
    ramuancentaurlast: 0,
    ramuangriffinlast: 0,
    ramuanherolast: 0,
    ramuankucinglast: 0,
    ramuankudalast: 0,
    ramuankyubilast: 0,
    ramuannagalast: 0,
    ramuanphonixlast: 0,
    ramuanrubahlast: 0,
    ramuanserigalalast: 0,
    registered: false, // Dari else block
    reglast: 0, // Dari else block
    regTime: -1, // Dari else block
    rendang: 0,
    rhinoceros: 0,
    rhinocerosexp: 0,
    rhinoceroslastfeed: 0,
    rock: 0,
    roket: 0,
    role: "Newbie ㋡", // Dari else block. if block punya "Beginner"
    roti: 0,
    rtrofi: "perunggu", // Dari else block. if block punya "Perunggu"
    rubah: 0,
    rubahlastclaim: 0,
    rumahsakit: 0,
    sampah: 0,
    sand: 0,
    sapi: 0,
    sapir: 0,
    seedbayam: 0,
    seedbrokoli: 0,
    seedjagung: 0,
    seedkangkung: 0,
    seedkentang: 0,
    seedkubis: 0,
    seedlabu: 0,
    seedtomat: 0,
    seedwortel: 0,
    semangka: 0, // if (!user.registered)
    serigala: 0,
    serigalalastclaim: 0,
    sewa: false, // Dari else block
    shield: 0, // Dari else block. if (!isNumber(user.shield)) user.shield = false
    skill: "", // Dari else block
    skillexp: 0,
    snlast: 0,
    soda: 0,
    sop: 0,
    spammer: 0,
    spinlast: 0,
    ssapi: 0,
    stamina: 100,
    steak: 0,
    stick: 0,
    strength: 30, // Dari else block
    string: 0,
    stroberi: 0, // if (!user.registered)
    superior: 0,
    suplabu: 0,
    sushi: 0,
    sword: 0,
    sworddurability: 0,
    tigame: 50,
    tiketcoin: 0,
    title: "", // Dari else block. if block punya title = 0
    tomat: 0,
    tprem: 0,
    trash: 0,
    trofi: 0,
    troopcamp: 0,
    tumiskangkung: 0,
    udang: 0,
    udangbakar: 0,
    umpan: 0,
    uncommon: 0,
    unreglast: 0,
    upgrader: 0,
    vodka: 0,
    wallet: 0,
    warn: 0,
    weapon: 0,
    weapondurability: 0,
    wolf: 0,
    wolfexp: 0,
    wolflastfeed: 0,
    wood: 0,
    wortel: 0,
    // Fields from `if (user)` that were not in `else` or had different logic
    kingdom: true, // dari if (user)
    // ownerDate: -1, // dari if (!user.registered), digabung dengan ownerTime
    // catexp: 0, // digabung dengan catngexp
    // glimit: 20, // dari if (user)
    // intelligence: 0, // if block punya 0, else punya 10. Dipilih 10 dari else.
    // mana: 0, // if block punya 0, else punya 20. Dipilih 20 dari else.
    // money: 0, // if block punya 0, else punya 100. Dipilih 100 dari else.
    // strength: 0, // if block punya 0, else punya 30. Dipilih 30 dari else.
  };
}

export function getDefaultChat() {
  return {
    isBanned: false,
    welcome: true, // Diambil dari else block. if block: welcome = false
    detect: false,
    sWelcome: '',
    sBye: '',
    sPromote: '',
    sDemote: '',
    delete: false, // Diambil dari else block. if block: delete = true (namun sepertinya salah karena di if (chat.delete) ada return) Seharusnya false.
    antiLink: false,
    antiLinkAll: false, // Hanya ada di if (chat)
    antiCall: false, // Diambil dari else block. if block: anticall = true (nama beda)
    antiFoto: false, // Hanya ada di if (chat)
    antiVideo: false, // Hanya ada di if (chat)
    antiSticker: false, // Hanya ada di if (chat)
    antiAudio: false, // Hanya ada di if (chat)
    viewonce: false, // Hanya ada di if (chat)
    antiBadword: false, // Hanya ada di if (chat)
    simi: false,
    expired: 0,
    nsfw: false, // Hanya ada di if (chat)
    premnsfw: false, // Hanya ada di if (chat)
  };
}

export function getDefaultAkinatorData() {
  return {
    sesi: false,
    server: null,
    frontaddr: null,
    session: null,
    signature: null,
    question: null,
    progression: null,
    step: null,
    soal: null,
  };
}

export function getDefaultSettings() {
  return {
    self: false,
    autoread: true,
    antiCall: true,
    restrict: true,
    image: true,
    gif: false,
    teks: false,
    doc: false,
    loc: false,
    autorestart: true,
    restartDB: 0,
  };
}
